### ISSUE TITLE
O que é um método idempotente?

### ISSUE THREAD

**Issue by GabiStz** [sganderla/questionamentos#1]
Olá professor, gostaria de saber por que o Post é um método idempotente?

**Comment by TEXTBr** [comment]
https://developer.mozilla.org/pt-BR/docs/Glossary/Idempotent

**Comment by sganderla** [comment]
Quando falamos em **_idempotência_** em API’s:

- Métodos: GET, PUT, DELETE, HEAD e OPTIONS são **_idempotentes_**.
- Métodos: POST não é **_idempotente_**.

> **Por que o **POST** não é idempotente?** 
> A principio uma chamada **POST** realiza a tentativa de registrar um novo elemento no banco de dados da aplicação, gerado assim uma alteração do estado e no banco de dados. Como cada requisição gera um novo valor, sempre teremos retornos diferentes a cada requisição.

> O **GET** é considerado **_idempotente_** pois ele pode retornar a mesma resposta em **_N_** requisições.

> Já o **PUT** altera os valores de um elemento do banco de dados. Quando realizamos a primeira requisição é feito a alteração do elemento e é retornado um status 200, porém, se realizarmos novas requisições com os mesmo valore, teremos uma resposta igual a primeira requisição. Desta forma consideramos o PUT como **_idempotente_**, pois, a partir da primeira chamada, sempre teremos o mesmo valor de resposta.

> O mesmo ocorre com o método **DELETE**.

Podemos concluir que quando disponibilizamos uma API REST, devemos nos preocupar com os serviços que irão consumir os endpoints. Muitos comentem erros e realizam chamadas duplicadas, assim podendo afetar o resultado esperado ou recebendo algum tipo de exception. Também a casos de chamadas intencionais, por exemplo, quando ocorre um timeout, muitos serviços fazem uma nova chamada para o endpoint. Com isso devemos utilizar idempotência, prevenindo alguns erros e também aplicando uma boa prática.

Referências:
[https://xuenqui.medium.com](https://xuenqui.medium.com/idempot%C3%AAncia-uma-boa-pr%C3%A1tica-a-se-utilizar-em-servi%C3%A7os-rest-633c38f4d7c0)
