### ISSUE TITLE
Como faço para lincar as Services com as Controllers? Como eu faço os Ifs dentro das Services? 

### ISSUE THREAD

**Issue by Eduardo-Souza2000** [sganderla/questionamentos#2]
Boa tarde, estou com duvida como fazemos para lincar ou melhor para usar em conjunto as condições dentro da service com a controller, além disso, os ifs dentro da service, como faria eles, tentei e nao consegui, tem alguma literatura ou algum link que possamos ler para compreender melhor essa questão?

**Comment by sganderla** [comment]
No nosso primeiro exemplo utilizamos a injeção de dependência para acessarmos os Repositórios das Controllers.  

```java
@Autowired
private NomeRepository nomeRepository;
```
Agora utilizaremos a mesma ideia para acessarmos as Services das Controllers.

```java
@Autowired
private NomeServices nomeServices;
```
Temos outra forma de realizarmos a injeção de dependência, que é utilizando o **_Constructor_** da classe.

```java
@RestController
public void NomeController {
      
    private NomeService nomeService;

    public NomeController(final NomeService nomeService){
        this.nomeService = nomeService;
    }
}
```

**Comment by sganderla** [comment]
Temos duas maneiras, podemos utilizar o bloco tradicional de condicionais:

```java
if(true == true) {
    System.out.println("Condicional = verdadeiro");
} else {
    System.out.println("Condicional = falso");
}
```

Ou você pode utilizar os Asserts

```java
Assert.isTrue(Condição, "Mensagem de Erro");
Assert.isNull(Objeto, "Mensagem de Erro");
...
```
