### ISSUE TITLE
Qual é a diferença entre uma classe de serviço (service class) e uma classe de controle (controller class) no Spring Framework?

### ISSUE THREAD

**Issue by MCastegnaro** [sganderla/questionamentos#3]

**Comment by sganderla** [comment]
### Controller

Nossa classes **_Controllers_** são as "Portas de entrada e saída da nossa aplicação". 
Ou seja, é aonde os clientes (Angular, Vue, React..) irão interagir com nossa aplicação;

```java
@RestController
@RequestMapping(value = "/api/nome")
public void NomeController{
    ...
}
```

É importante gerenciar o tipo de **_Controller_** que deseja. Se ela será uma `@Controller` ou `@RestController `  #5 

-----------------------

### Services

Nossas classes **_Services_** são responsáveis por executar nossas validações, restrições, formatações, etc. 

```java
@Service
public void NomeService{
    ...
}
```
