### ISSUE TITLE
Qual a diferença de @RestController para @Controller?

### ISSUE THREAD

**Issue by GabiStz** [sganderla/questionamentos#5]

**Comment by sganderla** [comment]
```java
@Controller
```
    
> - É uma especialização do `@Component`;
> - Para se comportar como API REST, é necessário utilizarmos a anotação `@ResponseBody` em todos os endpoints; 
> - Disponível a partir da versão V1 do _**Spring**_;  
> - Com a anotação `@Controller` é possível renderizar template **_HTML_**;  

```java
@RestController
```

> - É uma especialização do `@Controller`, ou seja, a anotação `@RestController` tem as suas funcionalidade e também acaba herdando as funcionalidades da anotação `@Controller`;  
> - Os comportamentos de **_API REST,_** já vem por default. Ou seja, as respostar são serializadas no formato **JSON, XML**...   
> - Disponível a partir da versão V4 do **_Spring_**;
> - Recomendado quando não for serializar template **_HML_**;
