### ISSUE TITLE
Em todos os Controller eu preciso passar @RequestMapping(value = "/api/nomeController")?

### ISSUE THREAD

**Issue by GabiStz** [sganderla/questionamentos#6]

**Comment by sganderla** [comment]
Quando utilizamos a anotação `@RequestMapping` declaramos que todos os demais **_endpoints_** internos a **_Controller_** serão acessível a partir desse link.

**_EX:_** declaramos uma Controller com `@RequestMapping`

```java
@RestController
@RequestMapping(value = "/api/nome")
public void nomeController{

    @GetMapping
    @GetMapping("/{id}")
    @PostMapping
    @PutMapping
    @DeleteMapping

}

```

Isso significa que todos os métodos da **_Controller_** será acessada a partir da **url** `http://localhost:8080/api/nome`

### **Importante,** 
Não necessariamente o `@RequestMapping(value = "/api/nome")` usará o nome da **_Controller_**.  Porem é uma boa pratica padronizar os nomes.
